project:
  type: website

website:
  title: "Доклад о Kappa Architecture"
  navbar:
    left:
      - href: index.qmd
        text: О докладе
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/ML-Big-Data-Kappa/ML-Big-Data-Kappa
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Части доклада"
        contents:
          - href: links.qmd
            text: Полезные материалы
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
